[workspace]
resolver = "2"
members = ["vitreo", "examples/minimal", "examples/live-backdrop"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/frostlinelab/vitreo"

[workspace.dependencies]
wgpu = "30"
bytemuck = { version = "1", features = ["derive"] }

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
