[workspace]
resolver = "2"
members = ["vitreo", "vitreo-egui", "examples/minimal", "examples/live-backdrop"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/frostlinelab/vitreo"

[workspace.dependencies]
wgpu = "30"
bytemuck = { version = "1", features = ["derive"] }
winit = "0.30"
pollster = "0.4"
egui = "0.36"
egui-wgpu = "0.36"
egui-winit = "0.36"
log = "0.4"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
